#! /bin/sh
FRAGMENT=plugins/rascal_fragment_linux_0.1.6

if [ -d $HOME/eclipse/$FRAGMENT ]; then
	FRAGMENT=$HOME/eclipse/$FRAGMENT
elif [ -d $HOME/magnolia/eclipse/$FRAGMENT ]; then
	FRAGMENT=$HOME/magnolia/eclipse/$FRAGMENT
elif [ -d /usr/local/eclipse/$FRAGMENT ]; then
	FRAGMENT=/usr/local/eclipse/$FRAGMENT
else
	echo Unable to find rascal-fragment
	exit 1
fi


export LD_LIBRARY_PATH=$FRAGMENT/installed/lib/

$FRAGMENT/installed/bin/sdf2table -c -m Magnolia -o Magnolia.tbl
$FRAGMENT/installed/bin/baffle -wt -i Magnolia.tbl -o Magnolia.trm
$FRAGMENT/installed/bin/sdf2table -c -m MagnoliaCxx/MagnoliaCxx -o MagnoliaCxx.tbl
$FRAGMENT/installed/bin/baffle -wt -i MagnoliaCxx.tbl -o MagnoliaCxx.trm
$FRAGMENT/installed/bin/sdf2table -c -m Meta/MetaSyntax -o MetaXa.tbl -p .:$FRAGMENT/installed/share/sdf-library/library/

[ "$1" = "-i" ] && cp *.tbl ../../magnolia-eclipse/lang/ && echo installed
